### PR TITLE
single line comment tag causes error on weebly

### PR DESCRIPTION
**Pull request by azorpax**
single line comment tag causes error on weebly

### CODE REVIEW

**Comment by tjsnyder** [comment]
Can you provide us with a screenshot of the error possibly? We are using this code in production and I can't reproduce this.

**Comment by azorpax** [comment]
sorry. just found out that the cause of the error is not from the apps.
you can reproduce the error in blog page. 
1, create new post, 
2, drag any app into the page 
3, and drag another element/app beside the first element app.
screenshot 2016-06-13 20 55 10
4, publish it. 
5. go to dashboard 
6. and then go back to edit site. 
there you have the error now.

**Comment by M-Porter** [comment]
I still do not see any errors when following your reproduction steps. Can you screenshot/tell us what the error says?

**Comment by azorpax** [comment]
screenshot 2016-06-15 22 23 29

**Comment by puddi** [comment]
Hi @azorpax:

We've been able to replicate the issue with platform elements and columns within blog posts. The main issue is there's post content getting minified when it shouldn't be; single-line comments in platform elements are a symptom of this issue, not the cause.

As such, we're gonna close this PR out as we work on fixing the core issue. Thank you for reporting it, though!

**Pull request closed without merging**
